version: '3.1'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: laNacionRoot
      POSTGRES_PASSWORD: Pass123
      POSTGRES_DB: contact_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laNacionRoot -d contact_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: contact_api
    environment:
      DB_HOST: db
      DB_USER: laNacionRoot
      DB_PASSWORD: Pass123
      DB_NAME: contact_db
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  seeder:
    build: .
    container_name: contact_seeder
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: laNacionRoot
      DB_PASSWORD: Pass123
      DB_NAME: contact_db
      DB_PORT: 5432
    volumes:
      - .:/app
    command: sh -c "node seeds/seed.js"

volumes:
  postgres_data: